import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import * as T from '../../dist/vendor/three.module.min.js';
import {SpringSession,ARRIVAL} from '../../dist/level27-layout.js?v=60';
import {BATH_ARRIVAL,bathShowerAt,bathUnderShower,SHOWER_HEADS} from '../../dist/bathhouse-layout.js?v=60';
const source=fs.readFileSync('dist/main.js','utf8'),el={style:{},setAttribute(){},hidden:false,innerHTML:''},effects={clear(){},reset(){},update(){},stow(){}},street={level:11,cx:887766554433n,cz:-998877665544n,x:27.18,z:6.38,yaw:.7,pitch:-.12};
let updates=0,resets=0;
const c={T,BATH_ARRIVAL,bathShowerAt,bathUnderShower,SpringSession,state:{...street,velocity:new T.Vector3(),bottles:4,hydration:79},bathhouse:{active:false,presets:[0,0,0,0],focusDistance(){}},bathOrigin:null,bathTime:0,bathWetAge:0,springSession:new SpringSession(),springOpen:0,keys:new Set(),joy:{x:0,z:0},referenceView:null,interaction:null,time:7,waterInspection:{...effects,active:false},lensWater:effects,waterState:effects,bodyWater:effects,waterBubbles:effects,rainEffects:effects,waterImpact:effects,waterRipples:effects,weatherFlare:effects,exitAudio:effects,uiThemes:{applyLevel(){}},$:()=>el,renderer:{domElement:el,shadowMap:{}},camera:{far:480,updateProjectionMatrix(){}},resetCameraRig(){resets++;},waterPipeline:{...effects,setBathSteam(){},focus:{setSceneQuery(){}}},resize(){},toast(){},springJournal:'27',cityJournal:'11',fieldJournal:'10',eyelids:el,spring:{audio(){},focusDistance(){}},audio:{},exitScene:{update(){updates++;}},naturalShadows:{invalidate(){}}};vm.createContext(c);
function functions(start,end){vm.runInContext(source.slice(source.indexOf(start),source.indexOf(end)),c);}
functions('function enterSpring(){','function animateSpring(');functions('function enterBath(){','function animateBath(');functions('function use(){','function jump(){');
vm.runInContext('enterBath()',c);assert(c.bathhouse.active);assert.equal(c.state.cx,0n);assert.equal(c.state.z,BATH_ARRIVAL.z);assert.equal(c.state.bottles,4);
Object.assign(c.state,SHOWER_HEADS[2]);vm.runInContext('use()',c);assert.equal(c.bathhouse.presets[2],1);assert(!c.springSession.closing);vm.runInContext('use()',c);assert.equal(c.bathhouse.presets[2],2);vm.runInContext('use()',c);assert(c.springSession.closing);assert(c.springSession.tickClose(2.2,true));
const shower={x:c.state.x,z:c.state.z,yaw:c.state.yaw,pitch:c.state.pitch};vm.runInContext('enterSpring()',c);assert.equal(c.state.level,27);assert.equal(c.state.z,ARRIVAL.z);assert(c.bathhouse.active);vm.runInContext('leaveSpring()',c);assert.equal(c.state.level,11);assert.equal(c.state.x,shower.x);assert.equal(c.state.z,shower.z);assert.equal(updates,0,'must not stream street tiles using indoor coordinates');
vm.runInContext('leaveBath()',c);assert(!c.bathhouse.active);for(const k of Object.keys(street))assert.equal(c.state[k],street[k]);assert.equal(c.state.bottles,4);assert.equal(c.state.hydration,79);assert.equal(updates,1);
// F2 abandoning the spring uses the same two-stage unwind before teleport.
vm.runInContext('enterBath();enterSpring();leaveSpring(false);leaveBath(false)',c);for(const k of Object.keys(street))assert.equal(c.state[k],street[k]);assert(!c.bathhouse.active);assert.equal(c.springSession.origin,null);
console.log('Production E controls: glass door → reception → individual hot shower → eyes closed → spring → same shower → exact BigInt street pose; F2 unwind and inventory preserved.',{cameraResets:resets});
