import assert from 'node:assert/strict';
import * as T from '../../dist/vendor/three.module.min.js';
import {field,stringSeed} from '../../dist/world.js';
import {makeGround} from '../../dist/ground.js';
import {createPacker,createUnpacker} from '../../dist/scene-packets.js';
import {createWaterSurface} from '../../dist/water-surface.js';
import {createMaterialFinish} from '../../dist/material-finish.js';
import {createWetGround} from '../../dist/wet-ground.js';
T.TextureLoader.prototype.load=function(url,ok){const t=new T.DataTexture(new Uint8Array([128,128,255,255]),1,1);queueMicrotask(()=>ok?.(t));return t;};
const surface=createWaterSurface({binding:{}});await surface.ready;
const f=field(-1n,0n,stringSeed('CHLORINE / ABUNDANCE / 10'),false),group=new T.Group();group.add(makeGround(f,0));
const packet=createPacker({T}).packChunk({group,field:f,pickups:[]}).packet;
const unpack=createUnpacker({T});unpack.acceptShared(packet);const chunk=unpack.unpackChunk(packet);
createMaterialFinish().attach(chunk.group);createWetGround().attach(chunk.group);surface.attach(chunk);
const m=chunk.group.children[0].material,s={vertexShader:T.ShaderLib.standard.vertexShader,fragmentShader:T.ShaderLib.standard.fragmentShader,uniforms:T.UniformsUtils.clone(T.ShaderLib.standard.uniforms)};m.onBeforeCompile(s,{});
const text=s.fragmentShader,base=text.lastIndexOf('diffuseColor.rgb=base;'),ca=text.lastIndexOf('float depthBelow='),out=text.lastIndexOf('#include <opaque_fragment>');
assert(base>0&&ca>base&&out>ca,'caustic must run AFTER worker terrain base, wet-ground and lighting');
assert(text.includes('outgoingLight+=vec3(.48,.66,.65)'));assert.equal(s.uniforms.v28Lake.value.y,f.lakeY);
assert(!text.slice(ca,out).includes('diffuseColor.rgb='),'caustics modulate light, not overwrite the soil');
assert(s.uniforms.uRuralSoil.value.isTexture,'worker transfer retained underlying terrain albedo');
console.log(JSON.stringify({pass:true,workerRoundtrip:true,terrainThenRadiance:true,soilPreserved:true,causticBeforeOpaque:true}));surface.dispose();unpack.dispose(chunk);unpack.disposeShared();
