import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';import fs from'node:fs/promises';
const root=process.env.TIKI_SITE_ROOT||new URL('../..',import.meta.url).pathname.replace(/\/$/,'');const browser=await chromium.launch({executablePath:'/tmp/tiki80-chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:960,height:680}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,500));});await p.route('**/*',async r=>{const u=new URL(r.request().url());let file=root+'/dist'+u.pathname;if(u.pathname==='/')file=root+'/dist/index.html';try{let body=await fs.readFile(file);if(u.pathname==='/main.js')body=Buffer.from(body.toString()+`\nwindow.qaGame={state,enterTiki,leaveTiki,use,setPlay,resetCameraRig,camera,renderer,exitScene,displayFilter,get frames(){return frameCount},renderOnce(){animateTiki(performance.now(),0,0)},get gardenActive(){return gardenActive},get room(){return currentTikiRoom()},get loading(){return bathLoading}};`);const ext=file.split('.').pop();await r.fulfill({status:200,contentType:({html:'text/html',js:'text/javascript',json:'application/json',webp:'image/webp',png:'image/png',jpg:'image/jpeg',css:'text/css'})[ext]||'application/octet-stream',body});}catch{await r.fulfill({status:404,body:'Missing '+u.pathname});}});await p.goto('http://terminal.local:4173/',{waitUntil:'load'});await p.waitForFunction(()=>window.qaGame,{},{timeout:180000});console.log('Actual game initialized');await p.evaluate(()=>window.qaGame.enterTiki());console.log('Actual room entered');await p.evaluate(()=>{const q=window.qaGame;q.setPlay(true);Object.assign(q.state,{x:1.48,z:-5.55,yaw:0,pitch:-.02});q.resetCameraRig();});
await p.evaluate(async()=>{const q=window.qaGame;await q.displayFilter.settleScene(()=>q.renderOnce());});
await p.screenshot({path:root+'/tests/tiki-garden-v81/results/restaurant-door-game.png'});
await p.keyboard.press('e');await p.waitForFunction(()=>window.qaGame.gardenActive&&!window.qaGame.loading,{},{timeout:240000});
await p.screenshot({path:root+'/tests/tiki-garden-v81/results/arrival-game.png'});console.log('Garden state',await p.evaluate(()=>({camera:window.qaGame.camera.position.toArray(),room:window.qaGame.room.scene.name}))); console.log('Garden actual game entry complete');console.log('errors',errors);
await p.keyboard.press('e');console.log(JSON.stringify({errors,returnedToRestaurant:await p.evaluate(()=>!window.qaGame.gardenActive),pose:await p.evaluate(()=>({x:window.qaGame.state.x,z:window.qaGame.state.z}))}));
}finally{await browser.close();}
