import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';import fs from'node:fs/promises';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,'');const browser=await chromium.launch({executablePath:'/workspace/scratch/85111d38430a/browser/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:800,height:600}}),errors=[];p.setDefaultTimeout(120000);p.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});p.on('console',m=>{if(m.type()==='error'){errors.push(m.text().slice(0,1000));console.log('CONSOLE',m.text().slice(0,600))}});await p.route('**/*',async r=>{const u=new URL(r.request().url());let file=root+'/dist'+(u.pathname==='/'?'/index.html':u.pathname);try{let body=await fs.readFile(file);if(u.pathname==='/main.js')body=Buffer.from(body.toString().replace('function animate(now){requestAnimationFrame(animate);','function animate(now){if(!window.qaFrameHold)requestAnimationFrame(animate);')+`\nwindow.qa0={hold(){window.qaFrameHold=true;},resume(){window.qaFrameHold=false;requestAnimationFrame(animate);},state,enterZero,leaveZero,leaveReferenceView,teleportFromMap,use,setPlay,resetCameraRig,camera,renderer,displayFilter,waterInspection,waterInventory,settings,resize,navigationMap,keys,get entryOrigin(){return zeroOrigin},get supplies(){return zeroSupplies},get world(){return zeroWorld},renderOnce(){animateZero(performance.now(),.016,.016)},get loading(){return bathLoading},get ready(){return ready}};`);await r.fulfill({status:200,body,contentType:({html:'text/html',js:'text/javascript',json:'application/json',webp:'image/webp',png:'image/png',jpg:'image/jpeg',css:'text/css'})[file.split('.').pop()]||'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Missing '+u.pathname});}});
await p.addInitScript(()=>localStorage.setItem('level10.preferences.v1',JSON.stringify({quality:'low',filter:'native',bob:false})));
const shot=async opts=>{await p.evaluate(()=>qa0.hold());await p.screenshot({...opts,timeout:120000});await p.evaluate(()=>qa0.resume());};
await p.goto('http://terminal.local:4173/',{waitUntil:'load'});await p.waitForFunction(()=>window.qa0,null,{timeout:240000});console.log('GAME INITIALIZED');let origin=await p.evaluate(()=>{const q=qa0;q.settings.filter='native';q.settings.quality='low';q.resize();return{x:q.state.x,z:q.state.z,cx:String(q.state.cx),cz:String(q.state.cz),level:q.state.level}});
await p.keyboard.press('F2');await p.locator('[data-teleport="level0-20"]').click();await p.waitForFunction(()=>!qa0.loading&&qa0.state.level===0);await shot({path:root+'/tests/level0-v96/results/game-atrium.png'});
const passage=await p.evaluate(()=>({spawnClear:!qa0.world.blocked(qa0.state.x,qa0.state.z,.23),rimIsSolid:!qa0.world.pitAt(qa0.state.x,qa0.state.z),centreIsPit:qa0.world.pitAt(302,70),landmarks:qa0.world.landmarks.length,eyeY:qa0.camera.position.y}));origin=await p.evaluate(()=>{const p=qa0.entryOrigin;return{x:p.x,z:p.z,cx:String(p.cx),cz:String(p.cz),level:p.level};});console.log('ENTRY',passage,origin);
await p.keyboard.press('F2');await p.locator('[data-teleport="level0-23"]').click();await p.waitForFunction(()=>!qa0.loading);await shot({path:root+'/tests/level0-v96/results/game-rare-manila.png'});
const rareDoor=await p.evaluate(()=>{const q=qa0,w=q.world,d=w.manila.nearest(q.state.x,q.state.z,q.state.yaw);if(!d)return {found:false};const before=d.target;w.manila.toggle(d);for(let i=0;i<30;i++)w.manila.update(.016,q.state.x,q.state.z);return {found:true,changed:before!==d.target,visibleCopy:w.manila.copy.root.visible,origin:w.manila.copy.origin};});console.log('RARE DOOR',rareDoor);
await p.keyboard.press('F2');await p.evaluate(()=>qa0.hold());await p.locator('[data-teleport="level0-return"]').click();const restored=await p.evaluate(()=>({x:qa0.state.x,z:qa0.state.z,cx:String(qa0.state.cx),cz:String(qa0.state.cz),level:qa0.state.level}));console.log('RETURN POSES',{origin,restored});await fs.writeFile(root+'/tests/level0-v96/results/game-entry.json',JSON.stringify({errors,origin,restored,passage,rareDoor},null,2));console.log('FINISHED',restored);if(JSON.stringify(origin)!==JSON.stringify(restored))throw Error('Origin not restored');if(errors.length)throw Error('Browser errors recorded');
}finally{await browser.close();}
