import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';import fs from'node:fs/promises';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,'');const browser=await chromium.launch({executablePath:'/workspace/scratch/f0eb35bc89ef/chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:900,height:660}}),errors=[];p.setDefaultTimeout(120000);p.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});p.on('console',m=>{if(m.type()==='error'){errors.push(m.text().slice(0,1000));console.log('CONSOLE',m.text().slice(0,600))}});await p.route('**/*',async r=>{const u=new URL(r.request().url());let file=root+'/dist'+(u.pathname==='/'?'/index.html':u.pathname);try{let body=await fs.readFile(file);if(u.pathname==='/main.js')body=Buffer.from(body.toString().replace('function animate(now){requestAnimationFrame(animate);','function animate(now){if(!window.qaFrameHold)requestAnimationFrame(animate);')+`\nwindow.qa0={hold(){window.qaFrameHold=true;},resume(){window.qaFrameHold=false;requestAnimationFrame(animate);},state,enterZero,leaveZero,teleportFromMap,use,setPlay,resetCameraRig,camera,renderer,displayFilter,waterInspection,waterInventory,settings,resize,navigationMap,keys,get supplies(){return zeroSupplies},get world(){return zeroWorld},renderOnce(){animateZero(performance.now(),.016,.016)},get loading(){return bathLoading},get ready(){return ready}};`);await r.fulfill({status:200,body,contentType:({html:'text/html',js:'text/javascript',json:'application/json',webp:'image/webp',png:'image/png',jpg:'image/jpeg',css:'text/css'})[file.split('.').pop()]||'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Missing '+u.pathname});}});
const shot=async opts=>{await p.evaluate(()=>qa0.hold());await p.screenshot({...opts,timeout:120000});await p.evaluate(()=>qa0.resume());};
await p.goto('http://terminal.local:4173/',{waitUntil:'load'});await p.waitForFunction(()=>window.qa0,null,{timeout:240000});console.log('GAME INITIALIZED');const origin=await p.evaluate(()=>{const q=qa0;q.settings.filter='native';q.settings.quality='low';q.resize();return{x:q.state.x,z:q.state.z,cx:String(q.state.cx),cz:String(q.state.cz),level:q.state.level}});
await p.evaluate(()=>qa0.enterZero(0));console.log('ZERO ENTERED',await p.evaluate(()=>({level:qa0.state.level,items:qa0.supplies.length,stats:qa0.world.stats()})));await shot({path:root+'/tests/level0-v2/results/game-arrival.png'});
await p.keyboard.press('f');await p.waitForFunction(()=>qa0.navigationMap.isOpen);await shot({path:root+'/tests/level0-v2/results/game-map.png'});console.log('MAP OPEN');await p.evaluate(()=>qa0.teleportFromMap({cx:0n,cz:0n,x:14.4,z:14.4,yaw:0}));if(!await p.evaluate(()=>!qa0.world.blocked(qa0.state.x,qa0.state.z)&&!qa0.world.pitAt(qa0.state.x,qa0.state.z)))throw Error('Unsafe map landing');console.log('MAP SAFE LANDING');
await p.evaluate(()=>{const q=qa0,p=q.supplies[0];Object.assign(q.state,{x:p.x,z:p.z+.75,yaw:0,pitch:-.5});q.resetCameraRig();q.use();});const pickup=await p.evaluate(()=>({inventory:qa0.waterInventory.length,inspection:qa0.waterInspection.active}));console.log('PICKUP',pickup);if(pickup.inventory!==1||!pickup.inspection)throw Error('Original almond inventory not integrated');await shot({path:root+'/tests/level0-v2/results/game-inspection.png'});await p.keyboard.press('q');if(await p.evaluate(()=>qa0.waterInventory.length)!==0)throw Error('Drink did not consume original item');console.log('DRINK OK');
await p.keyboard.press('F2');await p.locator('[data-teleport="level0-1"]').click();await p.waitForFunction(()=>!qa0.loading&&qa0.state.level===0);await shot({path:root+'/tests/level0-v2/results/game-arches.png'});console.log('F2 ARCHES');
await p.keyboard.press('F2');await p.locator('[data-teleport="level0-6"]').click();await p.waitForFunction(()=>!qa0.loading&&qa0.state.level===0);const breaker=await p.evaluate(()=>{const q=qa0,b=q.world.nearestBreaker(q.state.x,q.state.z,q.state.yaw);if(!b)throw Error('F2 breaker is unreachable');const before=q.world.stats().rebuildCount;q.use();q.renderOnce();return{id:b.id,off:q.world.circuits.has(b.id),local:q.world.powerAt(b.x,b.z),remote:q.world.powerAt(b.x+50,b.z),before,after:q.world.stats().rebuildCount};});console.log('BREAKER',breaker);if(!breaker.off||breaker.local>.05||breaker.remote!==1||breaker.before!==breaker.after)throw Error('Breaker circuit failed');await shot({path:root+'/tests/level0-v2/results/game-breaker-off.png'});
await p.evaluate(()=>{const q=qa0;q.world.ensure(300,300);q.world.ensure(q.state.x,q.state.z);if(!q.world.circuits.has('entry-circuit'))throw Error('Circuit lost after stream');q.use();q.renderOnce();if(q.world.powerAt(q.state.x,q.state.z)!==1)throw Error('Breaker did not restore power');});await shot({path:root+'/tests/level0-v2/results/game-breaker-on.png'});
await p.keyboard.press('F2');await p.locator('[data-teleport="level0-7"]').click();await p.waitForFunction(()=>!qa0.loading&&qa0.state.level===0);await shot({path:root+'/tests/level0-v2/results/game-furniture.png'});
const shader=await p.evaluate(()=>{const gl=qa0.renderer.getContext(),types=[gl.SAMPLER_2D,gl.SAMPLER_CUBE,gl.SAMPLER_3D,gl.SAMPLER_2D_SHADOW,gl.SAMPLER_2D_ARRAY];return qa0.renderer.info.programs.map(p=>{let count=0;for(let i=0;i<gl.getProgramParameter(p.program,gl.ACTIVE_UNIFORMS);i++){const u=gl.getActiveUniform(p.program,i);if(types.includes(u.type))count+=u.size;}return{name:p.name,count};});});const maxSamplers=Math.max(...shader.map(x=>x.count));console.log('SAMPLER MAX',maxSamplers);if(maxSamplers>16)throw Error('Sampler budget exceeded');
await p.evaluate(()=>qa0.leaveZero());const restored=await p.evaluate(()=>({x:qa0.state.x,z:qa0.state.z,cx:String(qa0.state.cx),cz:String(qa0.state.cz),level:qa0.state.level}));console.log('RESTORED',restored);if(JSON.stringify(origin)!==JSON.stringify(restored))throw Error('Origin pose not restored');await fs.writeFile(root+'/tests/level0-v2/results/game-flow.json',JSON.stringify({errors,origin,restored,pickup,breaker,maxSamplers,shader},null,2));if(errors.length)throw Error('Console errors recorded');
}finally{await browser.close();}
