import assert from 'node:assert/strict';import fs from 'node:fs';
import {field,stringSeed,roadProfile,cropSample,surfaceHeight,wheatAllowed,shoreGrassCover,pondMetrics}from '../../dist/world.js?v=35';
import {field as oldField,roadProfile as oldRoad,cropSample as oldCrop,surfaceHeight as oldHeight,wheatAllowed as oldWheat}from '../../dist/world-legacy.js?v=35';
import {macroPlan,patchworkContext}from '../../dist/patchwork.js?v=35';
const seed=stringSeed('CHLORINE / ABUNDANCE / 10');let birth=0,seams=0,lakeChecks=0,maxError=0;const report={seed};
for(let z=-2;z<=1;z++)for(let x=0;x<=1;x++){const f=field(BigInt(x),BigInt(z),seed,false),old=oldField(f.x,f.z,seed,false);for(let j=0;j<=64;j+=8)for(let i=0;i<=64;i+=8){const p=roadProfile(i,j,f,{}),q=oldRoad(i,j,old,{});for(const k of ['distance','rut','relief'])assert.equal(p[k],q[k]);assert.equal(surfaceHeight(i,j,f),oldHeight(i,j,old));assert.equal(cropSample(i,j,f,{}).crop,oldCrop(i,j,old,{}).crop);assert.equal(wheatAllowed(i,j,f),oldWheat(i,j,old));assert.equal(shoreGrassCover(i,j,f),0);birth++;}}
const bases=[[-5n,-2n],[5n,-12n],[12n,12n],[999999999999999999999999n,-999999999999999999999999n]];
for(const [x,z]of bases)for(let j=0;j<4;j++)for(let i=0;i<4;i++){const f=field(x+BigInt(i),z+BigInt(j),seed,false);for(const axis of [0,1]){const b=field(f.x+BigInt(axis===0),f.z+BigInt(axis===1),seed,false);for(let k=0;k<=64;k+=4){const a=axis===0?[64,k]:[k,64],bb=axis===0?[0,k]:[k,0],p=roadProfile(...a,f,{}),q=roadProfile(...bb,b,{});if(Math.abs(p.rut-q.rut)>1e-6||Math.abs(p.relief-q.relief)>1e-6||Math.abs(Math.min(16,p.distance)-Math.min(16,q.distance))>1e-6){console.log({x:String(f.x),z:String(f.z),axis,k,p,q});throw Error('seam detail');}for(const key of ['rut','relief'])maxError=Math.max(maxError,Math.abs(p[key]-q[key]));maxError=Math.max(maxError,Math.abs(Math.min(16,p.distance)-Math.min(16,q.distance)));assert.equal(cropSample(...a,f,{}).id,cropSample(...bb,b,{}).id);assert(Math.abs(shoreGrassCover(...a,f)-shoreGrassCover(...bb,b))<1e-6);seams++;}}}
assert(maxError<1e-6,'shared edge discrepancy');
for(let z=-3;z<=2;z++)for(let x=-5;x<=0;x++){const f=field(BigInt(x),BigInt(z),seed,false);if(f.type!=='pond')continue;const old=oldField(f.x,f.z,seed,false);for(const k of ['lakeId','lakeY','lakeSeed','rx','rz','angle'])assert.equal(f[k],old[k]);for(let j=0;j<=64;j+=4)for(let i=0;i<=64;i+=4){const m=pondMetrics(i,j,f);if(m.metres<=m.width+1.5){assert(Math.abs(surfaceHeight(i,j,f)-oldHeight(i,j,old))<1e-8,'shore terrain changed');assert.equal(shoreGrassCover(i,j,f),0,'grass intrudes on mudflat');lakeChecks++;}}}
const leaves=[],depths={},spans=[],access=[],gaps=[];let roads=0,small=0,large=0;
for(let z=-2;z<=2;z++)for(let x=-2;x<=2;x++){const m=macroPlan(BigInt(x),BigInt(z),seed);leaves.push(...m.leaves);roads+=m.roads.length;spans.push(m.bounds[1]-m.bounds[0],m.bounds[3]-m.bounds[2]);access.push(...m.turnarounds);for(const l of m.leaves){depths[l.depth]=(depths[l.depth]||0)+1;const w=l.bounds[1]-l.bounds[0],h=l.bounds[3]-l.bounds[2];assert(Math.min(w,h)>=39.999&&Math.max(w,h)>=59.999);if(Math.min(w,h)<=85&&Math.max(w,h)<=120)small++;if(w*h>55000)large++;}}
assert(Math.min(...spans)>=300&&Math.max(...spans)<=500);assert(small>0&&large>0);
for(const z of [-2,2]){const a=macroPlan(1n,BigInt(z),seed),b=macroPlan(2n,BigInt(z),seed),u=a.segments.filter(s=>s.id.endsWith(':south')).at(-1),v=b.segments.find(s=>s.id.endsWith(':south'));const gap=Math.hypot(u.x2+400-v.x1-800,u.z2-v.z1);assert(gap<1e-6);gaps.push(gap);}
const f=field(12n,12n,seed,false),clone=structuredClone(f);assert.deepEqual(roadProfile(32,32,f,{}),roadProfile(32,32,clone,{}));
Object.assign(report,{pass:true,birthSamples:birth,seamSamples:seams,maxSeamError:maxError,unchangedShoreSamples:lakeChecks,macroSpans:[Math.min(...spans),Math.max(...spans)],parcels:leaves.length,depths,smallParcels:small,largeParcels:large,roads,turnarounds:access.length,mainLaneReconnectionErrors:gaps,contextBytes:JSON.stringify(f.patch).length});
fs.writeFileSync(new URL('../../docs/roads-v35/checks.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
