import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const {createCanvas}=createRequire(import.meta.url)('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');globalThis.document={createElement:()=>createCanvas(1,1)};
const B=pathToFileURL((process.argv[2]||'/tmp/v38-baseline/dist')+'/').href,N=new URL('../../dist/',import.meta.url).href;
const [old,W,G,oldG,D,oldD,L,oldL,T,C,M,A,Budget]=await Promise.all([import(B+'world.js?v=37'),import(N+'world.js?v=38'),import(N+'ground.js?v=38'),import(B+'ground.js?v=37'),import(N+'dense-wheat.js?v=38'),import(B+'dense-wheat.js?v=37'),import(N+'lake-shape.js?v=38'),import(B+'lake-shape.js?v=37'),import(N+'vendor/three.module.min.js'),import(N+'scene-packets.js?v=38'),import(N+'models.js?v=38'),import(N+'architecture-batch.js?v=38'),import(N+'ray-budget.js?v=38')]);
const seed=W.stringSeed('CHLORINE / ABUNDANCE / 10'),report={samples:0,heightMaxDelta:0,roadMaxDelta:0,shoreMaxDelta:0,plantChanges:0},fields=[];
for(const [x,z]of [[0n,0n],[-1n,0n],[0n,1n],[-2n,0n],[10n,0n],[22n,2n]]){
 const f=W.field(x,z,seed),b=old.field(x,z,seed);fields.push(f);assert.deepEqual(f.trees,b.trees);assert.deepEqual(f.shrubs,b.shrubs);assert.deepEqual(f.compounds,b.compounds);
 for(let zz=0;zz<=64;zz+=1.6)for(let xx=0;xx<=64;xx+=1.6){
  const h=W.surfaceHeight(xx,zz,f),bh=old.surfaceHeight(xx,zz,b);report.heightMaxDelta=Math.max(report.heightMaxDelta,Math.abs(h-bh));assert(Math.abs(h-bh)<1e-8);
  const r=W.roadProfile(xx,zz,f,{}),br=old.roadProfile(xx,zz,b,{});for(const k of ['distance','rut','relief','yard']){const d=Math.abs(r[k]-br[k]);report.roadMaxDelta=Math.max(report.roadMaxDelta,d);assert(d<1e-8,k);}
  assert.equal(W.cropSample(xx,zz,f,{}).crop,old.cropSample(xx,zz,b,{}).crop);assert.equal(W.wheatAllowed(xx,zz,f),old.wheatAllowed(xx,zz,b));
  for(const lake of f.roadLakes||[]){const d=Math.abs(L.pondShoreDistance(xx,zz,lake)-oldL.pondShoreDistance(xx,zz,lake));report.shoreMaxDelta=Math.max(report.shoreMaxDelta,d);assert(d<1e-8);}
  report.samples++;
 }
}
const f=fields[0],before=oldD.prepareWheatDetail(old.field(0n,0n,seed),'balanced'),after=D.prepareWheatDetail(f,'balanced');assert.equal(after.count,before.count);for(let i=0;i<after.patches.length;i++){assert.deepEqual(after.patches[i].matrices,before.patches[i].matrices);assert.deepEqual(after.patches[i].colors,before.patches[i].colors);}report.stemsUnchanged=after.count;
const ground=G.makeGround(f,0),snapshot=structuredClone(G.snapshotGround(f,0)),f2=structuredClone(f);G.restoreGround(f2,snapshot);const restored=G.makeGround(f2,0);for(const k of Object.keys(ground.geometry.attributes))assert.deepEqual(restored.geometry.attributes[k].array,ground.geometry.attributes[k].array);assert.deepEqual(restored.geometry.index.array,ground.geometry.index.array);report.groundCacheExact=true;
const chunk=M.makeChunk(fields[4],0,'balanced',new Set());chunk.detailPatches=D.prepareWheatDetail(fields[4],'balanced');const packer=C.createPacker({T,isSharedResource:M.isSharedModelResource,wind:M.wind}),decoder=C.createUnpacker({T,wind:M.wind,viewUniform:{value:new T.Vector3()}}),p=packer.packChunk(chunk),decoded=decoder.unpackChunk(structuredClone(p.packet,{transfer:p.transfer}));let arrays=0,surfaces=0;decoded.group.traverse(o=>{if(o.material?.userData.architectureBatch){surfaces++;const s={...T.ShaderLib.standard,uniforms:T.UniformsUtils.clone(T.ShaderLib.standard.uniforms)};o.material.onBeforeCompile(s,{});for(const n of ['uArchitecture128','uArchitecture256','uArchitecture512']){assert(s.uniforms[n].value.isDataArrayTexture);arrays++;}assert(s.fragmentShader.includes('flat varying vec4 vSurface'));}});report.packet={surfaces,arrays};assert(surfaces>0);decoder.dispose(decoded);decoder.disposeShared();
const b=new Budget.RayFrameBudget(),reserve=Budget.probeRayUpperBound(32,1)+Budget.probeRayUpperBound(96,4,3);b.grant(1);let used=0;while(b.credits>=reserve){await b.reserve(reserve);b.settle(reserve,reserve);used+=reserve;}assert(used<=24000);b.grant(2);assert.equal(b.credits,24000);assert.equal(b.spent,0);report.rayBudget={reservedPerProbe:reserve,cap:Budget.RAY_FRAME_BUDGET,peak:b.peak};
fs.writeFileSync(process.argv[3]||'/tmp/v38-regression.json',JSON.stringify(report,null,2));console.log(report);
