import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const {createCanvas}=createRequire(import.meta.url)(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');globalThis.document={createElement:()=>createCanvas(1,1)};
const B=new URL('../../dist/',import.meta.url).href,T=await import(B+'vendor/three.module.min.js'),{UrbanBatch}=await import(B+'urban-batch.js?v=69'),{createUrbanMaterials}=await import(B+'urban-materials.js?v=60'),U=await import(B+'urban-layout.js?v=60'),S=await import(B+'urban-streets.js?v=69'),W=await import(B+'urban-streetwall.js?v=69'),{EXIT_CITY_Y:Y}=await import(B+'exit-route.js?v=60');
function build(staged){const b=new UrbanBatch(createUrbanMaterials()),p=U.cityBlockPlan(1,4,[]);const drain=t=>{let s;do{s=t.next();}while(!s.done);return s.value;};b.push(U.CITY_ORIGIN.x,0,U.CITY_ORIGIN.z,U.CITY_ANGLE);if(staged)drain(S.addBlockStreetsTask(b,p,0));else S.addBlockStreets(b,p,0);for(const spec of p.buildings){b.push(spec.x,Y+.15,spec.z,spec.ry);if(staged)drain(W.addStreetwallBuildingTask(b,{...spec,lod:0}));else W.addStreetwallBuilding(b,{...spec,lod:0});b.pop();}b.pop();const root=staged?drain(b.finishTask('check')):b.finish('check'),hash=crypto.createHash('sha256');root.traverse(o=>{if(!o.geometry)return;for(const [name,a]of Object.entries(o.geometry.attributes)){hash.update(name);hash.update(new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength));}});hash.update(JSON.stringify([b.colliders,b.walks,b.facades]));const result={sha256:hash.digest('hex'),stats:root.userData.cityStats,colliders:b.colliders.length,walks:b.walks.length};root.traverse(o=>o.geometry?.dispose());return result;}
const synchronous=build(false),out={synchronous};assert.equal(synchronous.sha256,'282fdf16318cf92bb605e41fdc7610713df96424efeb09ed742119379875265f','City geometry/collisions changed from V68');if(true){out.staged=build(true);assert.deepEqual(out.staged,synchronous);const mats={a:new T.MeshBasicMaterial(),b:new T.MeshBasicMaterial()},batch=new UrbanBatch(mats);batch.box('a',0,0,0,1,1,1);batch.box('b',2,0,0,1,1,1);let disposed=0;const old=T.BufferGeometry.prototype.dispose;T.BufferGeometry.prototype.dispose=function(){disposed++;return old.call(this);};const task=batch.finishTask('cancel');assert.equal(task.next().done,false);task.return();T.BufferGeometry.prototype.dispose=old;assert.equal(batch.parts.size,0);assert.equal(disposed,3);out.cancelledMergeDisposed=disposed;}
fs.writeFileSync(new URL('./results/city-check.json',import.meta.url),JSON.stringify(out,null,2));console.log(out);
