import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as T from '../../dist/vendor/three.module.min.js';
import {focalLengthForFov,hyperfocal,circleOfConfusion} from '../../dist/lens-optics.js';
import {createCameraFocus} from '../../dist/camera-focus.js';
import {CLOUD_LAYERS} from '../../dist/atmosphere.js';
import {createWaterPipeline} from '../../dist/water-pipeline.js';
import {WaterState} from '../../dist/water-state.js';
import {createWaterRipples} from '../../dist/water-ripples.js';
import {createLensWater} from '../../dist/lens-water.js';
assert.ok(Math.abs(hyperfocal(6)-2.577428571)<1e-8);
const f=focalLengthForFov(72);for(const z of [2,5,10,50,480])assert.ok(Math.abs(circleOfConfusion(z,2.58,f))<.1);
assert.ok(circleOfConfusion(14,1.2,f*4.5)>3);
const camera=new T.PerspectiveCamera(72,4/3,.08,480),focus=createCameraFocus();camera.position.set(.6,1.77,52);camera.updateMatrixWorld();
for(let i=0;i<180;i++)focus.update(1/60,camera);
assert.equal(focus.result.distance,2.58);assert.equal(camera.fov,72);assert.ok(focus.result.traces<=18);
focus.setZoom(4.5);for(let i=0;i<240;i++)focus.update(1/60,camera);
assert.equal(focus.result.zoom,4.5);assert.ok(camera.fov<19);assert.ok(Math.abs(focus.result.focalLength-f*4.5)<1e-6);
const paused=camera.fov;focus.setZoom(1);focus.update(1,camera,false);assert.equal(camera.fov,paused);
focus.reset(camera);assert.equal(camera.fov,72);assert.equal(focus.result.zoom,1);assert.equal(focus.result.mode,'wide');
assert.deepEqual(CLOUD_LAYERS.map(x=>x.altitude),[3000,1200,400]);
T.TextureLoader.prototype.load=function(url,onLoad){const t=new T.Texture();queueMicrotask(()=>onLoad?.(t));return t;};
let target=null;const draws=[];
const renderer={autoClear:true,extensions:{has:()=>true},capabilities:{maxSamples:4},toneMappingExposure:1.23,getRenderTarget:()=>target,setRenderTarget(t){target=t;},render(scene,camera){
 const mat=scene.children[0]?.material;draws.push({w:target?.width,h:target?.height,mat});
 for(const [k,u]of Object.entries(mat?.uniforms||{}))if(u.value?.isTexture&&new RegExp('\\b'+k+'\\b').test(mat.fragmentShader))assert.ok(u.value!==target?.texture&&u.value!==target?.depthTexture,'No active framebuffer feedback: '+k);
}};
const ripples=createWaterRipples(renderer),lens=createLensWater(renderer),waterState=new WaterState(),pipe=createWaterPipeline(renderer,{ripples,lens,waterState});await pipe.surface.ready;
const world=new T.Scene(),output=new T.WebGLRenderTarget(960,720),state={x:0,z:0,cx:0n,cz:0n};
pipe.update(1/60,camera,state,true,false,new T.Color(.4,.5,.6),new T.Vector3(0,1,0),0,0);
pipe.render(world,camera,null,960,720,output);pipe.render(world,camera,null,960,720,output);
assert.equal(draws.length,12);assert.deepEqual(draws.slice(0,6).map(x=>[x.w,x.h]),[[960,720],[480,360],[480,360],[480,360],[480,360],[960,720]]);
assert.equal(draws[0].mat,undefined);assert.equal(target,null);assert.equal(camera.layers.mask,1);assert.equal(pipe.stats.taps,16);
assert.equal(pipe.stats.cocPasses,6);assert.equal(pipe.stats.depthCopies,0);
pipe.contextLost();pipe.render(world,camera,null,1280,720,output);assert.equal(pipe.stats.compositeWidth,640);
pipe.dispose();lens.dispose();ripples.dispose();output.dispose();
const report={passed:true,wideFocalMM:f,sixMMHyperfocalMeters:hyperfocal(6),wideFarRadiusPixels:circleOfConfusion(480,2.58,f),teleNearFocusRadiusPixels:circleOfConfusion(14,1.2,f*4.5),maxAFQueriesPerSecond:8,normalSkySamples:14,highSkySamples:17,halfResolutionPasses:4,cloudAltitudes:CLOUD_LAYERS.map(x=>x.altitude)};
console.log(JSON.stringify(report,null,2));if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(report,null,2));
