import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {createCanvas,loadImage}=createRequire(import.meta.url)(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');globalThis.document={createElement:()=>createCanvas(1,1)};
const base=new URL('../../dist/',import.meta.url).href;const T=await import(base+'vendor/three.module.min.js');
async function decode(url,w,h){const im=await loadImage(url.pathname),c=createCanvas(w,h);c.getContext('2d').drawImage(im,0,0,w,h);return{data:new Uint8Array(c.getContext('2d').getImageData(0,0,w,h).data),width:w,height:h};}
const {initializeBathTextures}=await import(base+'bath-textures.js?v=62'),{initializeSpaTextures}=await import(base+'spa-materials-v66.js'),{initializeChangingTextures,changingTextures}=await import(base+'changing-materials-v72.js');
const {initializeReceptionTextures73,receptionTextures73}=await import(base+'reception-materials-v73.js');
await Promise.all([initializeReceptionTextures73(decode),initializeBathTextures(decode),initializeSpaTextures(decode),initializeChangingTextures(decode)]);
const {buildBathhouseSteps}=await import(base+'bathhouse-scene.js?v=73');const g=buildBathhouseSteps();let n=0,step,total=0,max=0;while(true){const t=performance.now();step=g.next();const cost=performance.now()-t;max=Math.max(max,cost);total+=cost;if(step.done)break;n++;}
const bath=step.value;bath.update(2,{x:0,z:12});bath.scene.updateMatrixWorld(true);let draws=0,tris=0;const missing=[];bath.scene.traverse(o=>{if(!o.isMesh)return;draws++;tris+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3*(o.isInstancedMesh?o.count:1);const a=o.geometry.attributes.position.array;assert([...a].every(Number.isFinite),o.name);if(o.material.isMeshStandardMaterial&&(o.material.name.startsWith('V72')||o.material.name.startsWith('V73'))&&!o.material.normalMap)missing.push(o.material.name);});assert.equal(missing.length,0,missing);assert.equal(Object.keys(changingTextures()).length,43);assert(bath.changing.areas.length===4);assert.equal(Object.keys(receptionTextures73()).length,43);assert.equal(bath.receptionAtmosphere.lights.length,5);assert.equal(bath.mirror.target.width,512);assert.equal(bath.mirror.target.height,256);assert(bath.changing.mirror.parent===bath.scene,'mirror must remain independently hideable after batching');
const report={passed:true,generatedMaps:86,newMaps:43,buildYields:n,totalBuildMilliseconds:total,longestBuildChunkMilliseconds:max,draws,triangles:tris,mirrorIndependent:true,rectAreaLights:5,notes:'Node build timings only, not measured gameplay FPS.'};fs.writeFileSync(new URL('./results/model.json',import.meta.url),JSON.stringify(report,null,2));console.log(report);
