import{chromium}from'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';import fs from'node:fs/promises';
const root=process.env.TIKI_SITE_ROOT||new URL('../..',import.meta.url).pathname.replace(/\/$/,'');const browser=await chromium.launch({executablePath:'/tmp/tiki80-chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:960,height:680}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,500));});await p.route('**/*',async r=>{const u=new URL(r.request().url());let file=root+'/dist'+u.pathname;if(u.pathname==='/')file=root+'/dist/index.html';try{let body=await fs.readFile(file);if(u.pathname==='/main.js')body=Buffer.from(body.toString()+`\nwindow.qaGame={state,enterTiki,leaveTiki,use,setPlay,resetCameraRig,camera,renderer,exitScene,displayFilter,waterInspection,waterInventory,settings,resize,get frames(){return frameCount},renderOnce(){animateTiki(performance.now(),0,0)},get gardenActive(){return gardenActive},get room(){return currentTikiRoom()},get loading(){return bathLoading}};`);const ext=file.split('.').pop();await r.fulfill({status:200,contentType:({html:'text/html',js:'text/javascript',json:'application/json',webp:'image/webp',png:'image/png',jpg:'image/jpeg',css:'text/css'})[ext]||'application/octet-stream',body});}catch{await r.fulfill({status:404,body:'Missing '+u.pathname});}});await p.goto('http://terminal.local:4173/',{waitUntil:'load'});await p.waitForFunction(()=>window.qaGame,{},{timeout:180000});console.log('Actual game initialized');await p.evaluate(()=>{window.qaGame.settings.filter='native';window.qaGame.settings.quality='low';window.qaGame.resize();});await p.evaluate(()=>window.qaGame.enterTiki());console.log('Actual room entered');await p.evaluate(()=>{const q=window.qaGame;q.setPlay(true);Object.assign(q.state,{x:1.48,z:-5.55,yaw:0,pitch:-.02});q.resetCameraRig();});
await p.evaluate(async()=>{const q=window.qaGame;await q.displayFilter.settleScene(()=>q.renderOnce());});
await p.screenshot({path:root+'/tests/tiki-garden-v85/results/restaurant-door-game.png'});
await p.keyboard.press('e');await p.waitForFunction(()=>window.qaGame.gardenActive&&!window.qaGame.loading,{},{timeout:240000});
await p.screenshot({path:root+'/tests/tiki-garden-v85/results/arrival-game.png'});console.log('Garden state',await p.evaluate(()=>({camera:window.qaGame.camera.position.toArray(),room:window.qaGame.room.scene.name}))); console.log('Garden actual game entry complete');console.log('errors',errors);
await p.evaluate(()=>{const q=window.qaGame;Object.assign(q.state,{x:5.88,z:-7.20,yaw:-Math.PI/2,pitch:-.37});q.resetCameraRig();q.renderOnce();});
console.log('query',await p.evaluate(()=>window.qaGame.room.vending.query(window.qaGame.camera)));await p.keyboard.press('e');await p.waitForFunction(()=>window.qaGame.room.vending.physics.size===1,null,{timeout:10000});
await p.evaluate(()=>{const q=window.qaGame;for(let i=0;i<160;i++)q.room.vending.tick(1/60,null,true);});
console.log('physics record',await p.evaluate(()=>[...window.qaGame.room.vending.physics.records.values()].map(r=>({type:r.type,p:[...r.position]}))));
await p.evaluate(async()=>{const q=window.qaGame;Object.assign(q.state,{x:6.20,z:-7.20});q.resetCameraRig();const r=[...q.room.vending.physics.records.values()][0];const T=await import('/vendor/three.module.min.js');const c=new T.Vector3(0,r.profile.height*.5,0).applyQuaternion(new T.Quaternion(...r.quaternion)).add(new T.Vector3(...r.position));q.room.vending.object.updateMatrixWorld(true);c.applyMatrix4(q.room.vending.object.matrixWorld);q.camera.lookAt(c);q.camera.updateMatrixWorld(true);q.use();});
console.log('pickup',await p.evaluate(()=>({items:window.qaGame.waterInventory.length,kind:window.qaGame.waterInspection.variant?.kind,name:window.qaGame.waterInspection.name})));
if(!await p.evaluate(()=>window.qaGame.waterInventory.length===1&&window.qaGame.waterInspection.active))throw Error('Actual E pickup did not open the inspection');
await p.evaluate(async()=>{const q=window.qaGame;for(let i=0;i<45;i++)q.waterInspection.update(1/60,q.camera,true);await q.displayFilter.settleScene(()=>q.renderOnce());});await p.screenshot({path:root+'/tests/tiki-garden-v85/results/drink-inspection-game.png'});
await p.evaluate(()=>{const q=window.qaGame;q.waterInspection.clear();Object.assign(q.state,{x:0,z:7.13,yaw:Math.PI,pitch:0});q.resetCameraRig();q.use();});console.log(JSON.stringify({errors,returnedToRestaurant:await p.evaluate(()=>!window.qaGame.gardenActive),pose:await p.evaluate(()=>({x:window.qaGame.state.x,z:window.qaGame.state.z}))}));
await fs.writeFile(root+'/tests/tiki-garden-v85/results/game-errors.json',JSON.stringify(errors));
}finally{await browser.close();}
