import assert from 'node:assert/strict';
import * as T from '../../dist/vendor/three.module.min.js';
import {createWaterImpact} from '../../dist/water-impact.js?v=26';
const scene=new T.Scene(), pulses=[];
const impact=createWaterImpact(scene,{rng:()=>.5,onRipple:p=>pulses.push(p)});
const state={cx:10n**45n,cz:-(10n**45n),x:2,z:3,yaw:0,velocity:{x:0,z:-1},waterDepth:.20};
assert.equal(impact.group.children.length,3);
assert.equal(impact.diagnostics.capacity,1536);
assert.deepEqual(impact.group.children.map(m=>m.geometry.instanceCount),[10,1536,384]);
const attributes=()=>impact.group.children.flatMap(m=>Object.values(m.geometry.attributes));
impact.emit(1.8,state,0);
assert.equal(pulses.length,1);
assert(pulses[0].strength<0);
assert.equal(pulses[0].cx,state.cx);
const snapshots=attributes().map(a=>({version:a.version,values:Array.from(a.array)}));
for(let i=0;i<12;i++)impact.update(1/60,state,null,true);
attributes().forEach((a,i)=>{
  assert.equal(a.version,snapshots[i].version,'animation must not upload attributes');
  assert.deepEqual(Array.from(a.array),snapshots[i].values,'animation must not write positions');
});
assert(impact.group.children[0].material.uniforms.uTime.value>.19);
const oldOrigin=impact.group.children[0].geometry.attributes.iOrigin.array[0];
state.cx+=1n;impact.update(0,state,null,true);
assert(Math.abs(impact.group.children[0].geometry.attributes.iOrigin.array[0]-oldOrigin+64)<.0001);
for(let i=0;i<120;i++)impact.update(1/60,state,null,true);
assert(pulses.some(p=>p.strength>0));
assert(pulses.every(p=>Number.isFinite(p.radius)&&Number.isFinite(p.x)&&Number.isFinite(p.z)));
assert.equal(impact.group.visible,false);
for(let i=0;i<60;i++)impact.emit(1.8,state,0);
assert.deepEqual(impact.group.children.map(m=>m.geometry.instanceCount),[10,1536,384]);
impact.group.children.forEach(mesh=>{
  for(const a of Object.values(mesh.geometry.attributes))assert(Array.from(a.array).every(Number.isFinite));
  assert(mesh.material.vertexShader.includes('#include <fog_vertex>'));
  assert(mesh.material.fragmentShader.includes('#include <fog_fragment>'));
  assert(mesh.material.uniforms.fogColor);
  assert.equal(mesh.material.forceSinglePass,true);
});
state.cx+=10n**90n;impact.update(0,state,null,true);
assert.equal(impact.group.visible,false,'huge teleport clears before Number(BigInt)');
impact.emit(.18,state,0);
assert.equal(impact.group.children[0].geometry.attributes.iJet.array[1],0,'ordinary stride has no tall column');
const crown=impact.group.children[0].geometry;
assert.equal(crown.index.count,3456,'768 crown + 384 column triangles');
impact.update(130,state,null,true);
assert(impact.group.children[0].material.uniforms.uTime.value<128);
impact.dispose();impact.dispose();assert.equal(scene.children.length,0);
console.log(JSON.stringify({ok:true,checks:['3 bounded draws','no animation attribute writes','signed delayed ripple feedback','BigInt rebase','teleport clear','ordinary-stride jet suppression','fog hooks and uniforms','topology','time rebase','idempotent disposal'],diagnostics:impact.diagnostics},null,2));
