import assert from 'node:assert/strict';

import * as T from '../../dist/vendor/three.module.min.js';
import {createRainRenderer} from '../../dist/rain-render.js?v=26';
let seed=381;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const scene=new T.Scene(),camera=new T.PerspectiveCamera(60,1.6,.1,100);
camera.position.set(32,2,32);const state={cx:100000000000000000001n,cz:-100000000000000000002n,x:32,z:32,yaw:0,velocity:{x:3,z:2}};
let roof=-1000,water=true;const hits=[];
const rain=createRainRenderer(scene,{rng,onRipple:p=>hits.push(p),surfaceQuery:()=>({y:0,roof,water})});
for(let i=0;i<120;i++)rain.update(1/60,{state,camera,chunks:new Map(),rain:1});
assert.equal(rain.statistics.batches,3);assert.equal(rain.rain.geometry.instanceCount,2600);
assert.equal(rain.rings.children[0].geometry.instanceCount,576);assert.equal(rain.rings.children[1].geometry.instanceCount,96);
assert(hits.length>70&&hits.length<95,'Rain rate bounded and actually emits water disturbances');
assert(hits.every(p=>p.cx===state.cx&&p.cz===state.cz&&p.strength>=.003&&p.strength<=.007));
assert.deepEqual(rain.uniforms.uRainCameraVelocity.value.toArray(),[3,0,2]);
const attrs=rain.rings.children.flatMap(m=>Object.values(m.geometry.attributes).filter(a=>a.isInstancedBufferAttribute));
const versions=attrs.map(a=>a.version),seedVersion=rain.rain.geometry.attributes.rainSeed.version;
rain.update(.005,{state,camera,chunks:new Map(),rain:0});
assert.deepEqual(attrs.map(a=>a.version),versions,'No per-frame surface particle buffer upload');
assert.equal(rain.rain.geometry.attributes.rainSeed.version,seedVersion,'Rain seeds immutable');
assert(!rain.rain.visible&&rain.rings.visible,'Finished rain preserves fading impact effects');
state.cx+=1n;state.x-=64;camera.position.x-=64;
rain.update(.005,{state,camera,chunks:new Map(),rain:0});
assert.deepEqual(rain.uniforms.uRainRebase.value.toArray(),[-64,0]);
assert.deepEqual(attrs.map(a=>a.version),versions,'Chunk rebase uses uniform, no per-particle transforms');
rain.update(3,{state,camera,chunks:new Map(),rain:0});assert(!rain.rings.visible,'Impact lifetime expires in elapsed wall time');
roof=6;const before=hits.length;
for(let i=0;i<120;i++)rain.update(1/60,{state,camera,chunks:new Map(),rain:1});
assert.equal(hits.length,before,'Shelter suppresses ground impacts');
assert(Array.from(rain.uniforms.uRainFloor.value.image.data).every(x=>x===6),'Rain vertex clipping sees roof support');
rain.update(1/60,{state,camera,chunks:new Map(),rain:1,active:false});assert(!rain.rain.visible&&!rain.rings.visible);
rain.clear();assert(!rain.rain.visible&&!rain.rings.visible);assert.equal(rain.uniforms.uRainStrength.value,0);
rain.dispose();assert.equal(scene.children.length,0);
const report={pass:true,waterCallbacks:before,checks:['Instanced geometry capacities','bounded water hit rate','immobile seed buffers','camera relative velocity','birth-only attribute uploads','BigInt chunk rebasing without buffers','real elapsed lifetime','roof support clipping','sheltered impact suppression','inactive and dry hiding','clear and disposal'],statistics:rain.statistics};
console.log(JSON.stringify(report,null,2));
