import {chromium} from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,''),shots=process.argv.slice(2);if(!shots.length)shots.push('pool','arrival','fountain');
const browser=await chromium.launch({executablePath:'/tmp/tiki80-chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
 await page.route('**/*',async route=>{const u=new URL(route.request().url()),file=u.pathname==='/__garden.html'?root+'/tests/tiki-garden-v86/preview.html':root+'/dist'+u.pathname;try{const body=await fs.readFile(file),ext=file.split('.').pop();await route.fulfill({status:200,body,contentType:({html:'text/html',js:'text/javascript',json:'application/json',webp:'image/webp',png:'image/png',css:'text/css'})[ext]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Missing '+u.pathname});}});
 page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('CONSOLE ERROR',m.text().slice(0,2200))}});
 await page.goto('http://terminal.local:4173/__garden.html',{waitUntil:'load'});await page.waitForFunction(()=>window.qa?.ready,{},{timeout:240000});
 await page.evaluate(()=>{document.querySelector('nav')?.remove();document.querySelector('#status')?.remove();});await fs.mkdir(root+'/tests/tiki-garden-v86/results',{recursive:true});
 for(const shot of shots){if(shot==='bar'){await page.evaluate(()=>window.qa.setCamera([-2.79,1.63,5.47],[-8.07,1.65,4.95]));}else if(shot==='porch'){await page.evaluate(()=>window.qa.setCamera([.0,1.76,3.90],[.0,1.6,9.10]));}else if(shot==='porch-angle'){await page.evaluate(()=>window.qa.setCamera([3.92,1.68,4.57],[.0,1.52,9.25]));}else if(shot==='ceiling-ref'){await page.evaluate(()=>window.qa.setCamera([5.90,1.77,4.28],[-3.30,5.35,-5.74]));}else if(shot==='spray'){await page.evaluate(()=>{window.qa.setTime(0);window.qa.setTime(6.4);window.qa.setCamera([3.74,1.70,.25],[6.78,1.55,-2.40]);});}else if(shot==='footbath'){await page.evaluate(()=>window.qa.setCamera([-3.38,1.30,2.55],[-4.85,.97,.73]));}else if(shot==='botanist'){await page.evaluate(()=>window.qa.setCamera([5.55,1.52,-.9],[6.75,1.2,-2.8]));}else if(shot==='reaction'){await page.evaluate(()=>{window.qa.room.people.react(4);window.qa.setTime(5.1);window.qa.setCamera([6.0,1.65,-1.4],[6.75,1.51,-2.8]);});}else if(shot==='drinks'){await page.evaluate(()=>window.qa.setCamera([5.78,1.34,5.11],[6.43,.97,4.34]));}else if(shot==='vending'){await page.evaluate(()=>window.qa.setCamera([5.3,1.65,-5.63],[7.45,1.04,-7.20]));}else if(shot==='lights'){await page.evaluate(()=>window.qa.setCamera([5.36,1.4,4.2],[5.36,3.04,5.23]));console.log(await page.evaluate(()=>window.qa.room.object.children.map(o=>({name:o.material.name,count:o.geometry.attributes.position.count}))))}else await page.evaluate(s=>window.qa.pose(s),shot);await page.screenshot({path:root+'/tests/tiki-garden-v86/results/'+shot+'.png'});console.log('Captured',shot);}
 console.log(JSON.stringify({errors,stats:await page.evaluate(()=>window.qa.stats),meshes:await page.evaluate(()=>window.qa.room.object.children.map(o=>({name:o.material?.name,tri:(o.geometry?.attributes.position.count||0)/3})).sort((a,b)=>b.tri-a.tri).slice(0,12))}));
}finally{await browser.close();}
