import {chromium} from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';import fs from 'node:fs/promises';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,''),browser=await chromium.launch({executablePath:'/tmp/tiki80-chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[];try{const page=await browser.newPage({viewport:{width:1100,height:760}});page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text().slice(0,1500));console.log('CONSOLE ERROR',m.text().slice(0,500));}});await page.route('**/*',async route=>{const u=new URL(route.request().url()),file=root+'/dist'+(u.pathname==='/'?'/index.html':u.pathname);try{let body=await fs.readFile(file);if(u.pathname==='/main.js')body=Buffer.from(body.toString().replace('function animate(now){','function animate(now){if(window.qaFreeze){requestAnimationFrame(animate);return;}')+`\nwindow.qa={state,scene,settings,resize,teleportCity,camera,renderer,exitScene,setPlay,resetCameraRig,navigationMap,keys,async returnAt(s){if(millingActive){const p=returnPoint(s);millingPose.x=p.x;millingPose.z=p.z;millingPose.yaw=Math.atan2(-p.tx,-p.tz);millingPose.pitch=-.02;cameraRig.reset({x:p.x,z:p.z,yaw:millingPose.yaw,pitch:millingPose.pitch,eyeY:returnFloor(p.x,p.z)+1.77});return;}if(!millingReturn)millingReturn=createMillingReturn();millingWarm=true;const p=returnPoint(s),w=returnToWorld(p.x,p.z);await teleportCity({...w,yaw:RETURN_MOUTH.angle+Math.atan2(-p.tx,-p.tz),pitch:-.02,label:'返程验证'});enterMilling();millingPose.x=p.x;millingPose.z=p.z;},get route(){return {loading:bathLoading,active:millingActive,warm:millingWarm,progress:returnProgress.value,x:millingPose.x,z:millingPose.z,level:state.level,ready:neighbourhoodReady(),rural:millingRuralReady,chunks:chunks.size,queue:queue.length,building:!!activeBuild,workerBusy:chunkStream.busy,streamStart:chunkStream.starting}},async mouthAt(s){const p=returnPoint(s),w=returnToWorld(p.x,p.z);await teleportCity({...w,yaw:RETURN_MOUTH.angle+Math.atan2(-p.tx,-p.tz),pitch:-.02,label:"装卸通道"});},cityPoint:cityLocalPose};`);await route.fulfill({status:200,contentType:({html:'text/html',js:'text/javascript',css:'text/css',webp:'image/webp',png:'image/png',json:'application/json'})[file.split('.').pop()]||'application/octet-stream',body});}catch{await route.fulfill({status:404,body:u.pathname});}});await page.goto('http://terminal.local:4173/',{waitUntil:'load'});await page.waitForFunction(()=>window.qa,{},{timeout:240000});console.log('game ready');await page.evaluate(async()=>{const{cityToWorld}=await import('/urban-layout.js?v=return-1');window.qa.settings.filter='native';window.qa.settings.quality='low';window.qa.resize();await window.qa.teleportCity({...cityToWorld(72,176),yaw:Math.PI/2,pitch:-.035,label:'补建街区'});});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.qaFreeze=true;resolve();})));await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/after-infill.png'});await page.evaluate(()=>window.qaFreeze=false);console.log('infill captured');
console.log('infill counts',await page.evaluate(async()=>{const {cityBlockPlan}=await import('/urban-layout.js?v=return-1');return [-1,0].flatMap(x=>[0,1,2,3].map(z=>({x,z,count:cityBlockPlan(x,z).buildings.length})));}));
await page.evaluate(async()=>{const{returnWaypoint}=await import('/milling-return-layout.js');await window.qa.teleportCity(returnWaypoint());});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.qaFreeze=true;resolve();})));await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/city-mouth.png'});await page.evaluate(()=>window.qaFreeze=false);console.log('mouth captured');

await page.evaluate(()=>window.qa.mouthAt(24));await page.waitForFunction(()=>window.qa.route.warm,null,{timeout:120000});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.qaFreeze=true;resolve();})));await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/city-before-gate.png'});await page.evaluate(()=>{window.qaFreeze=false;window.qa.setPlay(true);window.qa.keys.add('KeyW');});await page.waitForFunction(()=>window.qa.route.active,null,{timeout:120000});await page.evaluate(()=>window.qa.keys.delete('KeyW'));console.log('keyboard portal entry',await page.evaluate(()=>window.qa.route));
for(const s of[29,106,194]){await page.evaluate(s=>window.qa.returnAt(s),s);await page.waitForFunction(s=>window.qa.route.active&&Math.abs(window.qa.route.progress-s/240)<.02,s,{timeout:120000});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.qaFreeze=true;resolve();})));await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/game-return-'+s+'.png'});await page.evaluate(()=>window.qaFreeze=false);console.log('route',s,await page.evaluate(()=>window.qa.route));}
await page.evaluate(()=>window.qa.returnAt(241));await page.waitForFunction(()=>window.qa.route.loading,null,{timeout:120000});await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/rural-loading.png'});await page.waitForFunction(()=>!window.qa.route.active&&!window.qa.route.loading,null,{timeout:240000});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.qaFreeze=true;resolve();})));await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/returned-level10.png'});await page.evaluate(()=>window.qaFreeze=false);console.log('returned',await page.evaluate(()=>window.qa.route));
// A second city trip covers the other album after native rural streaming.
await page.evaluate(()=>{window.qa.travelPromise=window.qa.teleportCity(window.qa.exitScene.waypoint('city-plaza'));});await page.waitForFunction(()=>document.querySelector('.city-transit')?.hidden===false);await page.screenshot({timeout:120000,path:root+'/tests/return-v84/results/city-loading.png'});await page.evaluate(()=>window.qa.travelPromise);console.log('city roundtrip completed');
console.log(JSON.stringify({errors}));await fs.writeFile(root+'/tests/return-v84/results/game-errors.json',JSON.stringify(errors));}finally{await browser.close();}
