import {chromium} from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs';
import fs from 'node:fs/promises';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,'');
const browser=await chromium.launch({executablePath:'/tmp/tiki80-chrome/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {const p=await browser.newPage({viewport:{width:1100,height:760}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,600));});await p.route('**/*',async r=>{const u=new URL(r.request().url());const path=root+'/dist'+(u.pathname==='/'?'/index.html':u.pathname);try{let body=await fs.readFile(path);if(u.pathname==='/main.js')body=Buffer.from(body.toString()+`\nwindow.qa={state,scene,settings,resize,teleportCity,camera,renderer,exitScene,setPlay,resetCameraRig};`);await r.fulfill({status:200,contentType:({html:'text/html',js:'text/javascript',css:'text/css',webp:'image/webp',png:'image/png',json:'application/json'})[path.split('.').pop()]||'application/octet-stream',body});}catch{await r.fulfill({status:404,body:u.pathname});}});
await p.goto('http://terminal.local:4173/',{waitUntil:'load'});await p.waitForFunction(()=>window.qa,{},{timeout:240000});console.log('baseline game ready');
const shapes=await p.evaluate(async()=>{const {worldToCity}=await import('/urban-layout.js?v=60');return window.qa.exitScene.colliders.map(q=>({...q,...worldToCity(q.x,q.z),ry:q.ry===undefined?undefined:q.ry-(awaitAngle())}));function awaitAngle(){return 0;}});await fs.writeFile(root+'/tests/return-alley/results/protected-world-rotations.json',JSON.stringify(shapes));
await p.evaluate(async()=>{const{cityToWorld}=await import('/urban-layout.js?v=60');window.qa.settings.filter='native';window.qa.settings.quality='low';window.qa.resize();await window.qa.teleportCity({...cityToWorld(72,176),yaw:Math.PI/2,pitch:-.035,label:'街区留白'});});await p.screenshot({path:root+'/tests/return-alley/results/before-empty-block.png'});console.log(JSON.stringify({errors,shapes:shapes.length}));
}finally{await browser.close();}
