// Export the production meshes/materials, not a substitute illustration.
import fs from 'node:fs';import {createRequire} from 'node:module';
const {createCanvas,loadImage}=createRequire(import.meta.url)('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const T=await import('../../dist/vendor/three.module.min.js'),A=await import('../../dist/almond-water-assets.js?v=46'),I=await import('../../dist/almond-water-inspection.js?v=46');
const P=process.argv[2]||'/tmp/almond-v46';fs.mkdirSync(P,{recursive:true});
await A.initializeAlmondTextures(async url=>{const im=await loadImage(url.pathname),c=createCanvas(im.width,im.height),ctx=c.getContext('2d');ctx.drawImage(im,0,0);return{data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height};});
const defs='\n#define NUM_DIR_LIGHTS 2\n#define NUM_POINT_LIGHTS 0\n#define NUM_SPOT_LIGHTS 0\n#define NUM_RECT_AREA_LIGHTS 0\n#define NUM_HEMI_LIGHTS 1\n#define NUM_DIR_LIGHT_SHADOWS 0\n#define NUM_POINT_LIGHT_SHADOWS 0\n#define NUM_SPOT_LIGHT_SHADOWS 0\n#define NUM_SPOT_LIGHT_MAPS 0\n#define NUM_SPOT_LIGHT_COORDS 0\n#define NUM_SPOT_LIGHT_SHADOWS_WITH_MAPS 0\n#define NUM_CLIPPING_PLANES 0\n#define UNION_CLIPPING_PLANES 0\n';
const vp='#version 300 es\nprecision highp float;precision highp int;\n#define attribute in\n#define varying out\nuniform mat4 modelMatrix,viewMatrix,modelViewMatrix,projectionMatrix;uniform mat3 normalMatrix;uniform vec3 cameraPosition;uniform bool isOrthographic;in vec3 position;in vec2 uv;in vec3 normal;\n';
const fp='#version 300 es\nprecision highp float;precision highp int;\n#define varying in\n#define texture2D texture\n#define textureCube texture\nout vec4 pc_fragColor;\n#define gl_FragColor pc_fragColor\nuniform vec3 cameraPosition;uniform mat4 viewMatrix;uniform bool isOrthographic;\nvec4 linearToOutputTexel(vec4 c){return c;}\n';
const include=s=>s.replace(/#include <([^>]+)>/g,(_,k)=>include(T.ShaderChunk[k]));
const shaders={},textures=[],textureIDs=new Map();let serial=0;
function bytes(file,a){fs.writeFileSync(P+'/'+file,Buffer.from(a.buffer,a.byteOffset,a.byteLength));return file;}
function texture(t){if(textureIDs.has(t))return textureIDs.get(t);const id=textures.length;textureIDs.set(t,id);if(t.isCubeTexture){textures.push({id,cube:true,faces:t.image.map((f,i)=>({file:bytes(`tex-${id}-${i}.bin`,f.image.data),width:f.image.width,height:f.image.height}))});return id;}
 textures.push({id,file:bytes('tex-'+id+'.bin',t.image.data),width:t.image.width,height:t.image.height,flipY:t.flipY,srgb:t.colorSpace===T.SRGBColorSpace,mip:t.generateMipmaps});return id;
}
function mesh(m){const mat=m.material,id=serial++,key=mat.isShaderMaterial?'glass':'opaque';if(!shaders[key]){const lib=T.ShaderLib.standard,s=mat.isShaderMaterial?{vertexShader:mat.vertexShader,fragmentShader:mat.fragmentShader,uniforms:mat.uniforms}:{vertexShader:lib.vertexShader,fragmentShader:lib.fragmentShader,uniforms:T.UniformsUtils.clone(lib.uniforms)};mat.onBeforeCompile(s,{});const d=defs+(mat.vertexColors?'#define USE_COLOR\n':'');const uniforms={},texs={};for(const[k,u]of Object.entries(s.uniforms)){if(u.value?.isTexture)texs[k]=texture(u.value);else if(u.value?.toArray)uniforms[k]=u.value.toArray();else if(typeof u.value==='number'||typeof u.value==='boolean')uniforms[k]=u.value;}Object.assign(uniforms,{opacity:1,roughness:mat.roughness??.15,metalness:mat.metalness||0,diffuse:[1,1,1]});shaders[key]={vertex:vp+d+(mat.vertexColors?'in vec3 color;\n':'')+include(s.vertexShader),fragment:fp+d+include(s.fragmentShader),uniforms,textures:texs};}
 const attributes={};for(const[k,a]of Object.entries(m.geometry.attributes))attributes[k]={file:bytes(`mesh-${id}-${k}.bin`,new Float32Array(a.array)),size:a.itemSize};return {id,key,model:m.matrixWorld.toArray(),attributes,index:m.geometry.index?bytes(`mesh-${id}-index.bin`,new Uint32Array(m.geometry.index.array)):null,count:m.geometry.index?.count||m.geometry.attributes.position.count};
}
const cases=[];const camera=new T.PerspectiveCamera(50,4/3,.025,20);camera.updateMatrixWorld();
for(const [kind,finish,label,closure,paint,angle]of [['thermos',0,0,0,0,0],['thermos',1,1,0,1,-.35],['thermos',2,2,0,2,.45],['glass',0,0,0,0,0],['glass',0,1,1,0,.2],['glass',0,2,2,0,-.25],['glass',0,3,0,0,.20]]){
 const v={kind,finish,label,closure,paint,seed:12},inspection=I.createAlmondInspection();inspection.begin(v,null,camera);for(let i=0;i<100;i++)inspection.update(1/60,camera,true);inspection.rotate(angle*150,-24);for(let i=0;i<18;i++)inspection.update(1/60,camera,true);inspection.scene.updateMatrixWorld(true);inspection.camera.updateMatrixWorld();const list=[];inspection.pose.traverse(m=>{if(m.isMesh)list.push(mesh(m));});
 const g=inspection.pose.children[0].userData.glass,u=g?.material.uniforms;cases.push({label:kind+'-'+finish+'-'+label+'-'+closure,meshes:list,view:inspection.camera.matrixWorldInverse.toArray(),projection:inspection.camera.projectionMatrix.toArray(),eye:[0,0,0],glass:u?{liquidTilt:u.liquidTilt.value.toArray(),fillHeight:u.fillHeight.value,liquidTime:u.liquidTime.value,liquidMotion:u.liquidMotion.value,glassAbsorption:u.glassAbsorption.value.toArray()}:null});inspection.dispose();
}
fs.writeFileSync(P+'/shaders.json',JSON.stringify(shaders));fs.writeFileSync(P+'/fixture.json',JSON.stringify({textures,cases}));console.log({output:P,cases:cases.length,textures:textures.length,shaderPrograms:Object.keys(shaders).length,triangles:cases.map(c=>[c.label,c.meshes.reduce((n,m)=>n+m.count/3,0)])});
