import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {createCanvas}=createRequire(import.meta.url)('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');globalThis.document={createElement:()=>createCanvas(1,1)};
const T=await import('../../dist/vendor/three.module.min.js');T.TextureLoader.prototype.load=function(url,ok){const t=new T.DataTexture(new Uint8Array([128,128,255,255]),1,1);queueMicrotask(()=>ok?.(t));return t;};
const {createWaterPipeline}=await import('../../dist/water-pipeline.js?v=46'),A=await import('../../dist/almond-water-assets.js?v=46');
const calls=[],renderer={autoClear:true,extensions:{has:()=>false},capabilities:{maxSamples:4},toneMappingExposure:1.23,target:null,getRenderTarget(){return this.target;},setRenderTarget(t){this.target=t;},clearDepth(){calls.push({depthClear:true});},render(scene,camera){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const selected=[];scene.traverseVisible(o=>{if(!o.isMesh||!camera.layers.test(o.layers))return;selected.push(o.name);for(const [n,u]of Object.entries(o.material.uniforms||{}))if(u.value?.isTexture){assert.notEqual(u.value,this.target?.texture,'color feedback: '+n);assert.notEqual(u.value,this.target?.depthTexture,'depth feedback: '+n);}});calls.push({scene,camera,layer:camera.layers.mask,target:this.target,names:selected});}};
const empty=new T.DataTexture(new Uint8Array(16),2,2),lens={washWeight:0,washAge:0,wetWeight:0,submerged:false,microbubbles:{texture:empty,weight:0},prepareField:()=>empty,physics:{fieldWidth:2,fieldHeight:2}},waterState={hasWater:false,wet:false,washWeight:0,flash:0};
const p=createWaterPipeline(renderer,{ripples:{binding:{}},lens,waterState,sky:null,fog:{compose:source=>source.texture}});await p.surface.ready;
const camera=new T.PerspectiveCamera(72,4/3,.08,480);camera.position.set(0,1.5,2);camera.lookAt(0,.15,0);camera.updateMatrixWorld();const world=new T.Scene(),g=new T.Group(),bottle=A.makeAlmondBottle({kind:'glass',finish:0,label:0,closure:0,paint:0,seed:0});g.add(bottle);world.add(g);world.updateMatrixWorld(true);const chunk={group:g,field:{},pickups:[{mesh:bottle}],colliders:[]};p.attach(chunk);
const out=new T.WebGLRenderTarget(960,720);
function frame(){calls.length=0;p.update(1/60,camera,{velocity:new T.Vector3()},true,true,new T.Color(),new T.Vector3(0,1,0),0,0);p.render(world,camera,null,960,720,out);assert.equal(calls.filter(c=>c.scene===world&&c.layer===1).length,1,'one opaque world render only');assert.equal(camera.layers.mask,1);assert.equal(renderer.autoClear,true);assert.equal(renderer.target,null);}
frame();assert(p.stats.bottleGlassVisible);assert.equal(calls.filter(c=>c.scene===world&&c.layer===8).length,1);
p.inspection.begin({kind:'glass',finish:0,label:1,closure:1,paint:0,seed:0},new T.Vector3(0,0,0),camera);frame();assert.equal(calls.filter(c=>c.scene===p.inspection.scene).length,2);assert.equal(calls.filter(c=>c.depthClear).length,1);
p.inspection.clear();p.inspection.begin({kind:'thermos',finish:0,label:1,closure:0,paint:0,seed:0},null,camera);frame();assert.equal(calls.filter(c=>c.scene===p.inspection.scene).length,1);
p.inspection.clear();p.removeBottle(bottle);A.releaseAlmondBottle(bottle);frame();assert(!p.stats.bottleGlassVisible);assert.equal(calls.filter(c=>c.scene===p.inspection.scene).length,0);assert.equal(calls.filter(c=>c.scene===world).length,1);
console.log('PASS actual water/optics/inspection render ordering, no framebuffer feedback, one opaque world render, glass-only layer, opaque-only thermos, no hidden inspection draws, render state restored');
